platform:
  - x86

install:
  - set PATH=C:\cygwin\bin;%PATH%
  - appveyor DownloadFile "http://raw.githubusercontent.com/swig/cccl/master/cccl"
  - appveyor DownloadFile "http://zlib.net/zlib128-dll.zip"
  - 7z x -ozlib zlib128-dll.zip
  - copy zlib\lib\zdll.lib zlib\lib\z.lib # FIXME
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%

build_script:
  - set CC=./cccl
  - set CXX=./cccl
  - bash -c "exec 0</dev/null; ./autogen.sh; ./configure --with-zlib=zlib; make CXXFLAGS='-D_HAS_EXCEPTIONS=0 -D_STATIC_CPPLIB'"

# disable automatic tests
test: off
