platform:
  - x86

branches:
  except:
    - coverity

skip_branch_with_pr: true

install:
  - set PATH=C:\cygwin\bin;%PATH%
  - set DIST=ots-windows-dist
  - appveyor DownloadFile "http://raw.githubusercontent.com/swig/cccl/master/cccl"
  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%

build_script:
  - set CC=./cccl
  - set CXX=./cccl
  - set CXXFLAGS='-D_HAS_EXCEPTIONS=0 -D_STATIC_CPPLIB'
  - bash -c "./autogen.sh && ./configure --enable-debug --prefix=$PWD/$DIST"
  - make

test_script:
  - make check

after_build:
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 10)
  - set ARCHIVE=ots-windows-%GIT_HASH%
  - if %APPVEYOR_REPO_TAG%==true (set ARCHIVE=ots-windows-%APPVEYOR_REPO_TAG_NAME%)
  - make install
  - mkdir -p %ARCHIVE%
  - cp %DIST%/bin/* %ARCHIVE%
  - 7z a %ARCHIVE%.zip %ARCHIVE%

artifacts:
  - path: /ots-windows-*.zip/

deploy:
  provider: GitHub
  auth_token:
    secure: "Mcg1hVyyuN6rVAvSj55POVX4C14JhWwL9UrP2tQAFTqk3Muke0ttyfYKZfeU4zAi"
  draft: true
  on:
    appveyor_repo_tag: true
