platform:
  - x86

install:
  - set PATH=C:\cygwin\bin;%PATH%
  - appveyor DownloadFile "http://raw.githubusercontent.com/swig/cccl/master/cccl"
  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%

build_script:
  - set CC=./cccl
  - set CXX=./cccl
  - set CXXFLAGS='-D_HAS_EXCEPTIONS=0 -D_STATIC_CPPLIB'
  - bash -c "./autogen.sh && ./configure --enable-debug --prefix=$PWD/dist"
  - make
  - make check
  - make install

# disable automatic tests
test: off

artifacts:
  # archive the built binaries in the ci.appveyor.com build report
  - path: dist\bin\*
